apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  namespace: java-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-container
          image: ameenmohammad/motivational-quotes-api


            
