apiVersion: v1
kind: Service
metadata:
  name: java-service
  namespace: java-ns
  labels:
    app: java-app
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8000       # Port exposed by the service
      targetPort: 8000 # Port on the pod
  type: NodePort

